zipf_alpha=1.03
read_percentage=30
protected_segment_ratio=0.65

workload.small_load.name=SMALL LOAD
workload.small_load.num_keys=1000000
workload.small_load.total_ops=10000000
workload.small_load.total_cache_capacity=250000
workload.small_load.eviction_budget=1

# workload.medium_load.name=MEDIUM LOAD
# workload.medium_load.num_keys=5000000
# workload.medium_load.total_ops=50000000
# workload.medium_load.total_cache_capacity=1250000
# workload.medium_load.eviction_budget=1

# workload.large_load.name=LARGE LOAD
# workload.large_load.num_keys=10000000
# workload.large_load.total_ops=100000000
# workload.large_load.total_cache_capacity=2500000
# workload.large_load.eviction_budget=1

# workload.very_large_load.name=VERY LARGE LOAD
# workload.very_large_load.num_keys=20000000
# workload.very_large_load.total_ops=200000000
# workload.very_large_load.total_cache_capacity=5000000
# workload.very_large_load.eviction_budget=1
